# -*- coding: utf-8 -*-
"""currencyConversion2bcontd.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zJrXj_b0Fh5xkvIXHR58ZmjIW-Z8iQnd
"""

pip install forex-python

from forex_python.converter import CurrencyRates

#class object creation
c=CurrencyRates()

print(c.get_rate('USD','INR'))

print(c.convert('USD','INR',20))

